### DISCUSSION TITLE
Getting the mod version from the `gradle.properties` file

### DISCUSSION THREAD

**Discussion by mineTomek** [Kira-NT/mc-publish#100] [Q&A] [answered]
Hi! Is there a way to replace all the version number instances with the version specified in the `gradle.properties` file? (`VERSION` in this step in my workflow):

```yaml
- uses: Kir-Antipov/mc-publish@v3.3
  with:
    modrinth-id: P9DbqD2L
    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
  
    github-tag: mc1.20.2-VERSION
    github-prerelease: true
    github-token: ${{ secrets._GITHUB_TOKEN }}
  
    name: Redstonery Mod VERSION for Minecraft 1.20.2
    version: mc1.20.2-VERSION
    version-type: alpha
    changelog-file: CHANGELOG.md
  
    loaders: |
      fabric
    game-versions: |
      1.20.2
```

This would be probably an extra step before this one that reads the version and puts it in a variable?

**Comment by Kira-NT** [comment, marked as answer]
I apologize for the delayed response. I've been busy working on lots of projects, including this one.

First of all, I recommend checking out [default values for different inputs](https://github.com/Kir-Antipov/mc-publish#-inputs), as there's a lot of unnecessary duplication in your config:
1) You do not need to specify the `loaders` input. Its value is already inferred by `mc-publish` since you are publishing a Fabric mod.
2) You do not need to specify `game-versions`. They are inferred from `fabric.mod.json`.
3) You do not need to specify `github-tag` as long as its value is exactly the same as the `version`'s.
4) You do not need to specify `github-prerelease` as long as its value correlates with the `version-type`'s (as it is in your case).

Also, I do not recommend using a custom GitHub token for that. Just use the regular `${{ secrets.GITHUB_TOKEN }}`. GitHub generates a new token for each run and then immediately expires it. This is much more secure than generating your own GitHub tokens and managing their lifetime manually.

After these changes, your configuration should look something like this:

```yaml
- uses: Kir-Antipov/mc-publish@v3.3
  with:
    name: Redstonery Mod VERSION for Minecraft MC_VERSION
    version: mcMC_VERSION-VERSION
    version-type: alpha
    changelog-file: CHANGELOG.md

    modrinth-id: P9DbqD2L # Can be moved to fabric.mod.json too
    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
  
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

Since you create releases via manual workflow dispatches and/or pushes to the `main` branch, there's no opportunity for `mc-publish` to automatically infer `name` and `version` values from. That's why I personally like triggering a release cycle by actually creating a release, where I can specify its name, version (i.e., tag), and changelog (i.e., release body), so these values can be propagated to Modrinth and CurseForge.

However, you are correct that you can use `gradle.properties` to provide those values to `mc-publish` manually. Via a quick duckduckgoing, I found this action - [christian-draeger/read-properties](https://github.com/christian-draeger/read-properties). Personally, I have never used it, so everything I mention below needs to be tested, but following the documentation of the said action, we can compose a configuration like so:

```yaml
- name: Read properties from gradle.properties
  id: read_properties
  uses: christian-draeger/read-properties@1.1.1
  with:
    path: gradle.properties
    properties: minecraft_version mod_version

- name: Upload assets to GitHub and Modrinth
  uses: Kir-Antipov/mc-publish@v3.3
  with:
    name: Redstonery Mod ${{ steps.read_properties.outputs.mod_version }} for Minecraft ${{ steps.read_properties.outputs.minecraft_version }}
    version: mc${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}
    version-type: alpha
    changelog-file: CHANGELOG.md

    modrinth-id: P9DbqD2L
    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
  
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

This way, `read-properties` reads Minecraft and mod versions from your `gradle.properties`, and then you can pass those values to `mc-publish`.

Hope this helps!
