### DISCUSSION TITLE
Loaders as an array

### DISCUSSION THREAD

**Discussion by Faboslav** [Kira-NT/mc-publish#107] [Q&A]
### Description
Hello there, i am trying to do little bit more complex action on my side, my github (matrix)context is like the following for this specific run:

```
2024-01-20T13:23:49.7956867Z   workflow-job-context: {
  "branch": "1.19.2",
  "mod_loader": "fabric",
  "supported_mod_loaders": [
    "fabric",
    "quilt"
  ],
  "curseforge_id": "779833",
  "modrinth_id": "ECOSu6pa"
}
```

If i want to use mentioned `supported_mod_loaders` in the `loaders` field as following:
`${{ matrix.supported_mod_loaders }}` it doesnt work with error:
`Error: The template is not valid. .github/workflows/publish.yml (Line: 139, Col: 30): A sequence was not expected`.

### Expected Behavior

Mentioned in general description.

### Actual Behavior

Mentioned in general description.

### Version

3.3.0

### Environment

GitHub Actions

**Comment by Kira-NT** [comment]
Hallo! This is not a bug, nor a problem on the side of `mc-publish`.

>Error: The template is not valid. .github/workflows/publish.yml (Line: 139, Col: 30): A sequence was not expected

This an error message from GitHub telling you that your workflow file is invalid.

I assume that [this is the workflow in question](https://github.com/Faboslav/friends-and-foes-beekeeper-hut/blob/master/.github/workflows/publish.yml).

Note that `supported_mod_loaders` is defined as a proper array:

```yaml
supported_mod_loaders: [fabric, quilt]
```

The problem is you try to provide it as an input to a GitHub Action *(which just happens to be `mc-publish`)* as is. [GitHub only allows strings and "stringifiable" values](https://docs.github.com/en/actions/learn-github-actions/expressions#functions) to be used within this context. So, if a complex object, like an array, is provided, GitHub will immediately fall flat on its back and spit a completely unhelpful error in your face.

Therefore, before providing any value to any action *(once again, the problem is not limited to `mc-publish`)*, you need to ensure that it's a string.

If you check the [`loaders`](https://github.com/Kir-Antipov/mc-publish#loaders) input in the README, you'll find the following example there:

```yaml
loaders: |
  fabric
  forge
  quilt
```

As you can see, this is not an array; it's a multiline string. It's not because I prefer working with strings over proper arrays and other complex objects, but rather because GitHub restricts action developers from receiving anything other than strings. Thanks to yet another brilliant decision at Microsoft, we find ourselves having to do double the amount of work:

 - You need to convert a perfectly fine array into a string.
 - I, on the other hand, need to convert that string back into the array you originally intended to provide.

But, well, it is what it is. To convert an array you obtained from the matrix to a string, you can use [the following syntax](https://docs.github.com/en/actions/learn-github-actions/expressions#join):

```yaml
loaders: ${{ join(matrix.supported_mod_loaders, ' ') }}
```

Hope this helps! :)

**Reply by Faboslav** [reply]
I am yet to try to use this with the cf and modrinth, but input to the actions is like the following now:

```
Run Kir-Antipov/mc-publish@v3.3.0
  with:
    github-token: ***
    github-tag: mc1.19.[2](https://github.com/Faboslav/friends-and-foes-beekeeper-hut/actions/runs/7595216208/job/20687536177#step:9:2)-2.0.0
    name: Friends&Foes - Beekeeper Hut 2.0.0 (fabric)
    version: fabric-mc1.19.2-2.0.0
    loaders: fabric\nquilt
    files: fabric/build/libs/!(*-@(dev|dev-shadow|sources|javadoc)).jar
```

So that should hopefully work, thank you for your quick response!

**Reply by Kira-NT** [reply]
One thing, though - it's strange that `\n` is rendered in the log. It's possible that GitHub doesn't support escape sequences in its expressions; I wouldn't be surprised at this point. If this is the case, you can use a regular space (`' '`) to separate the loaders. However, be aware that space separators are only allowed for `loaders`; other inputs require a proper newline sequence to work!

**Reply by Faboslav** [reply]
What about game-versions, i basically need to do something similar to this, i currently do this: `game-versions: ${{ matrix.branch }}\n${{ matrix.secondary_game_version }}`?

**Reply by Kira-NT** [reply]
So, I've examined the logs of your latest run, and it appears that the issue regarding GitHub's inability to interpret escape sequences as intended is indeed valid:

```shell
loaders: fabric\nquilt
game-versions: 1.20.4\n1.20.3
```

So, replace

```yaml
loaders: ${{ join(matrix.supported_mod_loaders, '\n') }}
```

with

```yaml
loaders: ${{ join(matrix.supported_mod_loaders, ' ') }}
```

Additionally, as you just mentioned, you define `game-versions` as follows:

```yaml
game-versions: ${{ matrix.branch }}\n${{ matrix.secondary_game_version }}
```

The problem is... YAML is just weird. In this case, `\n` is treated as a literal (i.e., `"\\n"`). Someone on StackOverflow has done an excellent job summarizing the various quirks associated with specifying strings in different ways, you can read about it [here](https://stackoverflow.com/a/21699210), highly recommended.

To fix the `game-versions` input, consider one of the following options:

```yaml
game-versions: "${{ matrix.branch }}\n${{ matrix.secondary_game_version }}"
```

or

```yaml
# If `secondary_game_version` is always present, you can combine the versions into a range.
# E.g., 1.20.4 || 1.20.5
game-versions: ${{ matrix.branch }} || ${{ matrix.secondary_game_version }}
```

or

```yaml
game-versions: |
  ${{ matrix.branch }}
  ${{ matrix.secondary_game_version }}
```

**Reply by Faboslav** [reply]
Thank you for your help once again, i have one last question, if i have multiloader setup, will mc-publish detect my meta files? Because if that is the case, maybe it would be better to define these things in the meta files for each mod loader.

**Reply by Kira-NT** [reply]
> Thank you for your help once again

I'm always glad to help!

> if i have multiloader setup

`mc-publish` doesn't know anything about it, nor does it care :) The only thing that matters is the files you are actually publishing; `mc-publish` reads metadata from them, namely from the primary file.

> maybe it would be better to define these things in the meta files for each mod loader

Absolutely! Most of the time, you don't even need to specify anything because `fabric.mod.json` automatically translates into `["fabric"]`, `mods.toml` into `["forge"]` or `["neoforge"]` (depending on the presence of a dependency on `neoforge`), and `quilt.mod.json` into `["quilt"]`. However, you can always override this behavior by specifying the loaders manually in the `mc-publish` section of your metadata:

```json
// fabric.mod.json
"custom": {
  "mc-publish": {
    "loaders": ["fabric", "quilt"]
  }
}
```

```
# mods.toml
[mc-publish]
    loaders = ["forge", "neoforge"]
```

**Comment by Faboslav** [comment]
Here you go: https://github.com/Faboslav/friends-and-foes-beekeeper-hut/blob/master/.github/workflows/publish.yml, it's currently work in progress, but i am testing it step by step and i am currently stuck on this thing.

**Reply by Kira-NT** [reply]
Thanks! I've just finished editing my response, so do check it out. I hope that it solves your problem!

**Comment by Faboslav** [comment]
Continuing the discussion, strangely enough, with that mentioned publish workflow

On curseforge site, there is only the Quilt mod loader, and fabric api as dependency
![Screenshot 2024-01-20 at 21 12 11](https://github.com/Kir-Antipov/mc-publish/assets/14179066/4c9feb04-ce99-42fa-a20d-fad2b0c0d659)

On modrinth, there is correctly both fabric and quilt, and also fabric api as a dependency

![Screenshot 2024-01-20 at 21 13 30](https://github.com/Kir-Antipov/mc-publish/assets/14179066/3e9cffd9-f234-4e40-9249-5e191b557464)

I am not sure, why is there fabric api even i dont mention that anywhere and if that is based on the mod meta files, why my other required dependencies are not there.

**Reply by Faboslav** [reply]
Run is available here: https://github.com/Faboslav/friends-and-foes-beekeeper-hut/actions/runs/7596537598/job/20690362618

For example, this is context for 1.19.2 fabric:
```
with:
    github-token: ***
    github-tag: mc1.19.2-2.0.0
    curseforge-id: 711899
    curseforge-token: ***
    modrinth-id: Kt[4](https://github.com/Faboslav/friends-and-foes-beekeeper-hut/actions/runs/7596537598/job/20690362618#step:9:4)RVKEd
    modrinth-featured: true
    modrinth-token: ***
    name: Friends&Foes - Beekeeper Hut 2.0.0 (fabric)
    version: fabric-mc1.1[9](https://github.com/Faboslav/friends-and-foes-beekeeper-hut/actions/runs/7596537598/job/20690362618#step:9:9).2-2.0.0
    loaders: fabric, quilt
    game-versions: 1.19.2
```
