### DISCUSSION TITLE
Curseforge keep complaining about loaders [Resource pack]

### DISCUSSION THREAD

**Discussion by bangetto** [Kira-NT/mc-publish#109] [Q&A] [answered]
I upload to both Modrinth and Curseforge, and after a while it became annoying to upload the same thing 2 times, so I started using this workflow, but when it publishes to curseforge it keeps complaining to specify a loader even tho I specified it every way I found while I was trying to debug the problem, but I'm out of ideas.
```yml
name: publish

on:
  release:
    types: [released]

jobs:
  publish-to-modrinth:
    runs-on: ubuntu-latest
    environment: github-actions
    strategy:
        max-parallel: 1
    steps:
       - name: Download the pack files
         uses: robinraju/release-downloader@v1.8
         id: download-files
         with:
           fileName: "*.zip"
           latest: true
           tarBall: false
           zipBall: false
           
       - name: Publish to Modrinth
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: "[${{ steps.download-files.outputs.tag_name }}] Viabackwards Plus"
           modrinth-id: v7n1ZsFg
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
           modrinth-unfeature-mode: subset
           files: '*.zip'
           loaders: minecraft
           game-versions: "[1.16.2,1.20.4]"
           game-version-filter: releases

  publish-to-curseforge:
    runs-on: ubuntu-latest
    environment: github-actions
    steps:
       - name: Download the pack files
         uses: robinraju/release-downloader@v1.8
         id: download-files
         with:
           fileName: "*.zip"
           latest: true
           tarBall: false
           zipBall: false

       - name: Publish to CurseForge
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: "[${{ steps.download-files.outputs.tag_name }}] Viabackwards Plus"
           curseforge-id: 821967
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
           curseforge-files: '*.zip'
           supported_mod_loaders: minecraft
           loaders: minecraft
           mod_loader: minecraft
           game-versions: "[1.16.2,1.20.4]"
           game-version-filter: releases
```

**Comment by Kira-NT** [comment, marked as answer]
Hi! Please note that you forgot to specify the `loaders` field. Here's the actual workflow that was used during the latest run:

https://github.com/ViaVersionAddons/ViaBackwards-Plus/actions/runs/7864141950/workflow#L46-L54

As you can see, it's not the same as the one you posted here. If you replicate the config you specified for Modrinth, the error will go away. So, just add:

```yaml
loaders: minecraft
```

to the workflow, and you should be good to go.

However, you do not need two separate jobs to publish to Modrinth and CurseForge, since you are trying to publish the exact same file(s). Thus, I strongly recommend merging your jobs into a single one:

```yaml
       - name: Publish to Modrinth and CurseForge
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: "[${{ steps.download-files.outputs.tag_name }}] Viabackwards Plus"
           files: '*.zip'
           loaders: minecraft
           game-versions: "[1.16.2,1.20.4]"

           modrinth-id: v7n1ZsFg
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

           curseforge-id: 821967
           curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
```

The less you write, the smaller the chances of stumbling upon a copy-paste error or any other type of typo ;)
