### DISCUSSION TITLE
Accidental publish targeting all versions?

### DISCUSSION THREAD

**Discussion by HeatherComputer** [Kira-NT/mc-publish#142] [Q&A]
![Screenshot_20250113_132133_Firefox.jpg](https://github.com/user-attachments/assets/e4bdd73b-6e30-4873-9905-0d89b44d1896)

With my latest usage of mc-publish, I noticed that the versions i had marked as supporting 1.21.2, 1.21.3 and 1.21.4 instead were marked as supporting literally every version under the sun.

This affected both modrinth and curseforge. I've attached a screenshot showing how it was displayed to the users.

I have a link to the workflow config file and relevant lines:
https://github.com/HeatherComputer/AdvancedBackups/blob/main/.github/workflows/publish.yml#L742-L767

The workflow run in question that caused this behaviour is visible at https://github.com/HeatherComputer/AdvancedBackups/actions/runs/12730116038/job/35482743892

Before I file a bug report, is there any blatant user error here that I'm somehow missing?

I'll be running more fine-grained testing hopefully later tonight, to see it's a one-off or consistent reproduction.

**Comment by Kira-NT** [comment]
> Before I file a bug report, is there any blatant user error here that I'm somehow missing?

Yes and no. "No" because `mc-publish` certainly shouldn't behave that way when provided with faulty input, and "yes" because the issue does stem from a faulty input on your side.

The core problem is that, for some reason, when `mc-publish` fails to parse a version range, it defaults to returning `VersionRange.ANY` instead of `VersionRange.NONE`. I could run `git blame` to track down the goof responsible for this unchuffly piece of code, but since I'm the only maintainer here, I already know that my past self is to blame :D

The issue in your configuration arises from `[1.21.2,1.21.3,1.21.4]`. You're treating it as an array, but it's not. It's supposed to be a range. Here are a few examples from the README:

```yaml
game-versions: |
  [1.16,1.16.5)
  >=21w37a <1.18.2
  1.19
```

The configuration supports intervals *(i.e., the syntax used by Forge and NeoForge for their dependency declarations)* and SemVer-ish version ranges *(i.e., the format used by Fabric and Quilt)*. Below are the correct ways to write what you intended:

```yaml
game-versions: [1.21.2,1.21.4]

# 1.21.4 is the latest release at the moment, so this form works too:
game-versions: [1.21.2,)

game-versions: >=1.21.2 <=1.21.4

# 1.21.4 is the latest release at the moment, so this form works too:
game-versions: >=1.21.2

# Alternatively, you can individually specify all the versions you want:
game-versions: |
    1.21.2
    1.21.3
    1.21.4
```

Also, I took a look at your project and noticed that you seem to specify dependencies on specific Minecraft versions directly in your mod metadata *(e.g., [for the affected 1.21.2 release](https://github.com/HeatherComputer/AdvancedBackups/blob/44e3ffcc3366cff3c5f8da90748717c5476ba4a3/neoforge/1.21.2/src/main/resources/META-INF/neoforge.mods.toml#L62))*. So, I would definitely recommend omitting the `game-versions` input entirely - `mc-publish` can handle this automatically.

Finally, it seems that `loaders`, `version-type`, and `version` are also unnecessary in your setup, **except** for Spigot, because currently `mc-publish` doesn't know how to read its metadata. However, for Fabric, NeoForge, Forge, and Quilt, this is not a problem, as they are fully supported out of the box.
