### DISCUSSION TITLE
Is there currently a way to set an uploaded resource pack as required?

### DISCUSSION THREAD

**Discussion by B1BU** [Kira-NT/mc-publish#154] [Q&A] [answered]
![image](https://github.com/user-attachments/assets/5c56f021-29e1-4681-9219-a3a172d70d71)

**Comment by Kira-NT** [comment, marked as answer]
Unfortunately, not at the moment! Will look into implementing this one a bit later.

**Reply by B1BU** [reply]
any news on this? it would be very useful to me

**Reply by Kira-NT** [reply]
Hi! No, to be quite frankly honest with you, I haven't given it much thought since it's a Modrinth-only feature.

That said, it does need to be implemented at some point. I'm not sure what it should look like, though. Modrinth supports the following file types: `required-resource-pack`, `optional-resource-pack`, `sources-jar`, `dev-jar`, `javadoc-jar`, and `signature`. I know how to auto-detect all of them except for the resource packs. Is there a way for mc-publish to infer whether a resource pack provided as an additional file is required or optional? Maybe there's some metadata inside it that I could extract this information from? Or perhaps we could add a custom field to the vanilla metadata for mc-publish to read?

Let me know if you have any ideas on how you'd like this feature to be implemented!

**Reply by B1BU** [reply]
Required resource packs are no different from normal resource packs, so there's no vanilla way to differentiate them. I was personally just thinking of it as something similar to how you define a dependency type, like this:

```yaml
jobs:
  build:
    # ...
    steps:
      # ...
      - uses: Kira-NT/mc-publish@v3
        with:
          # ...
          files: |
            Data Pack.zip
            Required Resource Pack.zip(required-resource-pack)
```

The reason I want this feature so much is because Modrinth provides an option to package data packs as mods, which is incredibly useful since mods get way more visibility, but for it to include the assets, the resource pack has to be marked as required, and there have been a few times when I forgot to set it as required before packaging the mod and got a bunch of confused people in the Discord server reporting that the mod was broken. 😅

**Reply by Kira-NT** [reply]
> I was personally just thinking of it as something similar to how you define a dependency type, like this:

This thought did cross my mind, mainly because people asking for Hangar support have already suggested attaching extra metadata to the specified files. However, I really dislike this solution for two reasons.

First of all, `files` already uses a special syntax (glob patterns), so somehow extending it seems like a very messy option. For example, braces already have two distinct meanings: they represent glob groups and, well, literal characters that might appear in a filename. I'm not sure how adding a third one into the mix would work without creating unnecessary ambiguity.

Then there's also the problem that a glob might *(and often does)* match multiple files, in which case a user could accidentally attach metadata to files they didn't intend to.

So I'd really like to avoid this particular solution.

---

One of the things I also thought about is that, since I'll eventually implement first-class support for resource packs and data packs, and mc-publish will be able to infer different properties from their internal metadata files, this information could simply be specified in `pack.mcmeta`. Minecraft ignores unknown fields for the sake of both backward and forward compatibility, so this shouldn't be an issue.

For example, 

```diff
 {
   "pack": {
     "pack_format": 15,
+    "required": true,
     "min_format": 15,
     "max_format": 200
   }
 }
```

Or:

```diff
 {
   "pack": {
     "pack_format": 15,
     "min_format": 15,
     "max_format": 200
   },
+  "mc-publish": {
+    "required": true
+  }
 }
```

What do you think about this one?

Also, since I don't personally publish mods that require additional resource packs, let me ask: if mc-publish detects that an additional asset is a resource pack and the user hasn't specified whether it's required or optional, which option should it default to?

> The reason I want this feature so much is [...]

Oh, don't worry, I'm not arguing against the feature! I just never got around to implementing it. Sorry you've had to manually set the asset type all this time, hopefully that will come to an end soon enough! :)

**Reply by B1BU** [reply]
> What do you think about this one?

Sounds good, although I imagine the "mc-publish" key option would be preferrable to avoid possible conflicts with something else.

Another option I thought of is maybe "files" alternatively accepting a list of values, which could be a normal glob string or a dict with metadata:

```yaml
- uses: Kira-NT/mc-publish@v3
  with:
    # ...
    files:
    - Cool Data Pack v1.0.0.zip
    - Cool Data Pack v1.0.0 Resources.zip:
        type: required-resource-pack
```

Or perhaps:

```yaml
- uses: Kira-NT/mc-publish@v3
  with:
    # ...
    files:
      Cool Data Pack v1.0.0.zip:
      Cool Data Pack v1.0.0 Resources.zip:
        type: required-resource-pack
```

> Also, since I don't personally publish mods that require additional resource packs, let me ask: if mc-publish detects that an additional asset is a resource pack and the user hasn't specified whether it's required or optional, which option should it default to?

As far as I know required resource packs are just a thing for data packs, since they can't come bundled with assets. I imagine defaulting to either option could be an issue if it was not the option the publisher intended, so I'd just leave it unset by default and let them pick.

> Oh, don't worry, I'm not arguing against the feature!

Oh, sorry, I didn't mean it to sound like that. I was just expressing how useful this feature would be for me, lol.
