### DISCUSSION TITLE
What would be the ideal setup for my multi-platform project?

### DISCUSSION THREAD

**Discussion by Andre601** [Kira-NT/mc-publish#29] [Q&A] [answered]
I have a project on Modrinth and looking at this action, I can see some good use in it.

However, the thing is that my project in question, namely [AdvancedServerList](https://github.com/Andre601/AdvancedServerList), is offering 4 distinct jar files for 4 different platforms to use on.
Each platform's jar file is located in `./:platform/target/AdvancedServerList-:platform-:version.jar`
`:platform` being the platform it was made for and `:version` being the version. So for example is a possible path `./bungeecord/target/AdvancedServerList-BungeeCord-1.5.1.jar`

So... What would be an optimal Action setup to publish the jar files to Modrinth without any major problems?

I already have a GitHub Action to automatically add the Jar files to a new GitHub Release, so Jar files would be already available from that Action: https://github.com/Andre601/AdvancedServerList/blob/master/.github/workflows/release.yml

**Comment by Kira-NT** [comment, marked as answer]
You can view your uploads as different versions of your plugin *(because technically they are different versions)*, therefore, taking into consideration the fact that mc-publish is able to publish one version to one platform at a time, since I do not want to turn it into a LHC control panel, you need 4 calls to mc-publish *(or 5, if you want to publish files to GitHub in batch, as you're doing right now)*. 

Considering all of the above, I would suggest you to replace your existing configuration with something like this:

```yaml
name: Build Jars

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'

    - name: Build jar
      run: mvn clean install

    - name: Upload BungeeCord assets to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.1
      with:
        name: 1.15.1 - BungeeCord
        version: 1.15.1
        files-primary: bungeecord/target/AdvancedServerList-*.jar
        files-secondary: ""
        loaders: bungeecord
        game-versions: |
          1.19
          1.19.1
          1.19.2
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Paper assets to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.1
      with:
        name: 1.15.1 - Paper
        version: 1.15.1
        files-primary: paper/target/AdvancedServerList-*.jar
        files-secondary: ""
        loaders: paper
        game-versions: |
          1.19
          1.19.1
          1.19.2
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Spigot assets to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.1
      with:
        name: 1.15.1 - Spigot
        version: 1.15.1
        files-primary: spigot/target/AdvancedServerList-*.jar
        files-secondary: ""
        loaders: spigot
        game-versions: |
          1.19
          1.19.1
          1.19.2
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Velocity assets to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.1
      with:
        name: 1.15.1 - Velocity
        version: 1.15.1
        files-primary: velocity/target/AdvancedServerList-*.jar
        files-secondary: ""
        loaders: velocity
        game-versions: |
          1.19
          1.19.1
          1.19.2
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

In order to make the configuration a little bit more readable and compact you could use [matrices](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs):

```yaml
name: Build Jars

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: bungeecord
            name: BungeeCord
          - platform: paper
            name: Paper
          - platform: spigot
            name: Spigot
          - platform: velocity
            name: Velocity
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '16'

    - name: Build jar
      run: mvn clean install

    - name: Get GitHub Release version
      id: release-version
      run: |
        version=$(echo ${{ github.event.release.tag_name }} | cut -d'v' -f2)
        echo "::set-output name=version::$version"

    - name: Upload ${{ matrix.name }} assets to GitHub and Modrinth
      uses: Kir-Antipov/mc-publish@v3.1
      with:
        name: ${{ steps.release-version.outputs.version }} - ${{ matrix.name }}
        version: ${{ steps.release-version.outputs.version }}
        files-primary: ${{ matrix.platform }}/target/AdvancedServerList-*.jar
        files-secondary: ""
        loaders: ${{ matrix.platform }}
        game-versions: |
          1.19
          1.19.1
          1.19.2
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

Hope this helps :)
