### DISCUSSION TITLE
Add extra info (loaders, game-versions, dependencies) to GitHub Release if created

### DISCUSSION THREAD

**Discussion by Andre601** [Kira-NT/mc-publish#60] [Ideas]
It would be a really nice feature to have the action auto-append information to the GitHub Release changelog based on the provided information.

That way would also a GitHub release mention dependencies for that release.

## Quick Mockup

Workflow file:
```yaml
jobs:
  publish:
    # ...
    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: Random-Modrinth-Project
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          curseforge-id: 0123456
          curseforge-token: ${{ secrets.CF_TOKEN }}
          
          dependencies: |
            sodium | depends | *
            fabric-api | depends | *
          
          loaders: |
            fabric
          
          game-versions: |
            1.19
            1.19.1
            1.19.2
            1.19.3
            1.19.4
          
          changelog: 'Added 1.19.4 support!'
          
          files-primary: 'build/libs/MyMod-*.jar'
          version: 1.5.0+mc1.19
```
the above would generate a changelog like this:

Added 1.19.4 support!

### Supported Loaders

| Loader | MC Version(s)                        |
| ------ | ------------------------------------ |
| fabric | 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4 |

### Dependencies

| Name       | Version | Download                                                                                                              | Type    |
| ---------- | ------- | --------------------------------------------------------------------------------------------------------------------- | ------- |
| sodium     | Any     | [Modrinth](https://modrinth.com/mod/sodium) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/sodium)         | Depends |
| fabric-api | Any     | [Modrinth](https://mordinth.com/mod/fabric-api) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fabric-api) | Depends |

----

The raw output (I made the tables fancy for readability sake):
```markdown
Added 1.19.4 support!

### Supported Loaders

| Loader | MC Version(s)                        |
| ------ | ------------------------------------ |
| fabric | 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4 |

### Dependencies

| Name       | Version | Download                                                                                                              | Type    |
| ---------- | ------- | --------------------------------------------------------------------------------------------------------------------- | ------- |
| sodium     | Any     | [Modrinth](https://modrinth.com/mod/sodium) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/sodium)         | Depends |
| fabric-api | Any     | [Modrinth](https://mordinth.com/mod/fabric-api) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fabric-api) | Depends |
```

I assume the biggest difficulty would be to generate the dependency table based on the provided dependencies and/or modrinth/curseforge sub-options.
Maybe a unordered list would be a better choice then?

Alternatively could a `github-dependencies` option be added to have specific dependencies declared...
Tho that would then either require you to provide the links yourself, or choose one of the platforms.

It's a "nice to have" idea at most, but it would be nice.
