### DISCUSSION TITLE
Is this good for packwiz modpacks?

### DISCUSSION THREAD

**Discussion by Daenyth** [Kira-NT/mc-publish#86] [Q&A]
I have a modpack built using packwiz, and I'd like to be able to automatically do releases etc using it - will this action work for that?

**Comment by Kira-NT** [comment]
I apologize for the late response. I am a bit overbooked at the moment.

`packwiz` is a tool for modpack creation, not a widely recognized modpack format in itself. So, it's entirely up to you what you use to create a modpack, you just need to export it to the format expected by a target platform, i.e., `.mrpack` for Modrinth and `.zip` for CurseForge. Fortunately, `packwiz` supports such functionality. Therefore, what you could do is:

1) Install `packwiz` on a GitHub Runner
2) Export your modpack to `.mrpack`
3) Export your modpack to `.zip`
4) Publish the modpack files via `mc-publish`

As a GitHub workflow, it would look something like this:

```yaml
name: publish-modpack

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: >=1.19

      # https://packwiz.infra.link/installation/
      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      # https://packwiz.infra.link/tutorials/hosting/curseforge/
      - name: Export modpack for CurseForge
        run: packwiz curseforge export

      # I suppose. The docs are missing
      - name: Export modpack for Modrinth
        run: packwiz modrinth export

      - name: Upload the modpack to GitHub, Modrinth, and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Put your project's Modrinth ID here
          modrinth-id: AAAAAAAA
          modrinth-files: *.mrpack
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Put your project's CurseForge ID here
          curseforge-id: 0
          curseforge-files: *.zip
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-files: *.@(zip|mrpack)
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Update the list of supported loaders
          loaders: |
            fabric
            forge
            quilt

          # Update the list of supported Minecraft versions
          game-versions: >=1.20
          game-version-filter: releases
```

This workflow assumes that the contents of your modpack are stored in the root of your repository. Ensure you adjust this if the assumption does not hold.

Also, `mc-publish` cannot read the metadata of modpacks yet; however, this functionality is planned for v4.0. So you need to specify supported modloaders and Minecraft versions yourself.
